. - not necessary for now, maybe in the future
! - not urgent
!! - decently urgent
!!! - very urgent

- . More leagues coming!
- !! Add international competitions

- !!! Add player stats
- !!! Add stats per team

- ! Allow user to input multiple leagues and years
- . Allow user to set more specific params (on some methods)
- !! Add to_csv() method

- !! Add test suite
- !! Reformat TableParser, paramValidator a bit to make the code a bit neater
- !! Add documentation
- ! Update README.MD file
